<?xml version="1.0"?>
<package format="2">
  <name>ioniq5_ecan</name>
  <version>0.2.0</version>
  <description>Low-latency ROS 1 Noetic to Red Panda controller for a Hyundai Ioniq 5 HDA1 research vehicle.</description>

  <maintainer email="kelvin926@users.noreply.github.com">kelvin926</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>message_generation</build_depend>

  <depend>diagnostic_msgs</depend>
  <depend>libusb-1.0</depend>
  <depend>roscpp</depend>
  <depend>std_srvs</depend>

  <exec_depend>message_runtime</exec_depend>
  <exec_depend>python3-usb1</exec_depend>
  <test_depend>rostest</test_depend>

  <export/>
</package>
