#!/usr/bin/env python3
"""Decode every interpreted ECAN field from a raw CAN topic and publish the latest values.

Runs as a separate process so decoding never shares the control node's threads. The input is a
RawCanFrame topic from the control node (/ioniq5/can0/rx) or the receive-only logger
(/ioniq5/can_logger/rx). Definitions come from config/ecan_signals.json, generated by
generate_ecan_signals.py from the 2026-10-07 interpreted dictionary.
"""
from __future__ import annotations

import json
import math
import os
from pathlib import Path
import sys
import threading
import time


class Field:
    __slots__ = ("index", "positions", "start_bit", "bits", "little", "signed", "factor", "offset",
                 "last_byte")

    def __init__(self, index, spec):
        self.index = index
        self.start_bit = int(spec["start_bit"])
        self.bits = int(spec["bits"])
        self.little = spec["endian"] == "little"
        self.signed = bool(spec["signed"])
        self.factor = float(spec["factor"])
        self.offset = float(spec["offset"])
        self.positions = self._positions()
        self.last_byte = max(self.positions) // 8

    def _positions(self):
        # Same DBC bit convention as include/ioniq5_ecan/bit_codec.hpp, MSB first.
        if self.little:
            return list(range(self.start_bit + self.bits - 1, self.start_bit - 1, -1))
        positions, position = [], self.start_bit
        for _ in range(self.bits):
            positions.append(position)
            position = position + 15 if position % 8 == 0 else position - 1
        return positions

    def decode(self, data, as_int):
        if self.last_byte >= len(data):
            return None
        if self.little:
            raw = (as_int >> self.start_bit) & ((1 << self.bits) - 1)
        else:
            raw = 0
            for position in self.positions:
                raw = (raw << 1) | ((data[position >> 3] >> (position & 7)) & 1)
        if self.signed and raw & (1 << (self.bits - 1)):
            raw -= 1 << self.bits
        return raw * self.factor + self.offset


def load_definitions(path):
    document = json.loads(Path(path).read_text(encoding="utf-8"))
    signals = document["signals"]
    by_address = {}
    for index, spec in enumerate(signals):
        by_address.setdefault(int(spec["address"]), []).append(Field(index, spec))
    return signals, by_address


class Decoder:
    def __init__(self, signals, by_address):
        self.signals = signals
        self.by_address = by_address
        self.values = [math.nan] * len(signals)
        self.received = [0.0] * len(signals)
        self.lock = threading.Lock()

    def feed(self, address, data, now):
        fields = self.by_address.get(address)
        if not fields:
            return
        as_int = int.from_bytes(data, "little")
        with self.lock:
            for field in fields:
                value = field.decode(data, as_int)
                if value is not None:
                    self.values[field.index] = value
                    self.received[field.index] = now

    def snapshot(self, now):
        with self.lock:
            values = list(self.values)
            ages = [now - stamp if stamp else -1.0 for stamp in self.received]
        return values, ages


def main():
    # Resolve the package before importing rospy/init_node so default ROS logs stay local.
    import rospkg
    package = Path(rospkg.RosPack().get_path("ioniq5_ecan"))
    os.environ["ROS_HOME"] = str(package / "log/ros")
    os.environ["ROS_LOG_DIR"] = str(package / "log/ros/log")
    import rospy
    from ioniq5_ecan.msg import EcanSignals, RawCanFrame

    rospy.init_node("ecan_signal_decoder")
    definitions = rospy.get_param("~definitions", str(package / "config/ecan_signals.json"))
    input_topic = rospy.get_param("~input_topic", "/ioniq5/can0/rx")
    output_topic = rospy.get_param("~output_topic", "/ioniq5/ecan_signals")
    rate_hz = float(rospy.get_param("~rate_hz", 20.0))
    bus = int(rospy.get_param("~bus", 0))
    if rate_hz <= 0:
        raise ValueError("~rate_hz must be positive")

    signals, by_address = load_definitions(definitions)
    decoder = Decoder(signals, by_address)
    names = [signal["name"] for signal in signals]
    units = [signal["unit"] for signal in signals]

    def on_frame(frame):
        # Panda-returned TX echoes are this host's own frames, not vehicle traffic.
        if frame.returned or frame.rejected or (bus >= 0 and frame.bus != bus):
            return
        decoder.feed(frame.address, bytes(frame.data), time.monotonic())

    publisher = rospy.Publisher(output_topic, EcanSignals, queue_size=2)
    rospy.Subscriber(input_topic, RawCanFrame, on_frame, queue_size=4096, tcp_nodelay=True)
    rospy.loginfo("Decoding %d ECAN fields for %d IDs from %s to %s at %.1f Hz",
                  len(signals), len(by_address), input_topic, output_topic, rate_hz)
    rate = rospy.Rate(rate_hz)
    while not rospy.is_shutdown():
        values, ages = decoder.snapshot(time.monotonic())
        message = EcanSignals()
        message.stamp = rospy.Time.now()
        message.name = names
        message.unit = units
        message.value = values
        message.age_s = ages
        publisher.publish(message)
        try:
            rate.sleep()
        except rospy.ROSInterruptException:
            break
    return 0


if __name__ == "__main__":
    sys.exit(main())
